### ISSUE TITLE
Regression: Elements with "dialog" role trigger a landmark warning

### ISSUE THREAD

**Issue by traviskroberts** [dequelabs/axe-core#2556]
Expectation: When an element has a role of "dialog", it should not trigger the "All page content must be contained by landmarks" warning.

Actual: That warning is displayed.

Motivation: It appears the "dialog" exception was added in #1073 then removed in #2380. Not sure if that removal was a mistake or if it was intended.

**Comment by straker** [comment]
Thanks for the issue. We'll need to get this fixed in the Standards object.

**Comment by straker** [comment]
We're going to solve this by adding a selector options to our region rule. That way it's customizable if you need to exclude other elements.

**Comment by padmavemulapati** [comment]
Verified with the below test snippet:
`<div id="deque-dialog" class="deque-dialog" data-id="first-deque-dialog">`
 `<div>`
	`<button id="deque-dialog-trigger" class="deque-dialog-trigger hideFromQuizHint deque-button" aria-controls="deque-dialog"  data-id="first-deque-dialog">Show Dialog!</button>`
	  `</div>`
with out desribing `role` attribute its giving "region" rule failure with "All page content must be contained by landmarks"
![image](https://user-images.githubusercontent.com/47409579/97843034-9adf3880-1d0e-11eb-912e-4a4038c29b04.png)

![image](https://user-images.githubusercontent.com/47409579/97843393-396b9980-1d0f-11eb-99ea-842605437bc7.png)

after added `role="main"` attribute it got fixed and not throwing `region` failure.
`<div id="deque-dialog" class="deque-dialog" data-id="first-deque-dialog" role="main">`
 `<div>`
	`<button id="deque-dialog-trigger" class="deque-dialog-trigger hideFromQuizHint deque-button" aria-controls="deque-dialog" role="main"  data-id="first-deque-dialog">Show Dialog!</button>`
	  `</div>`

![image](https://user-images.githubusercontent.com/47409579/97843511-6ddf5580-1d0f-11eb-958f-9cc22ffb03d1.png)

![image](https://user-images.githubusercontent.com/47409579/97843562-851e4300-1d0f-11eb-92be-0ab39309aace.png)

**Comment by zolza** [comment]
Hey all, has this issue been fixed? I can see it happening in our modals, we use role="dialog" but still get `Document must have one main landmark` error showing when validating with axe. 
I am assuming the issue was meant to be fixed by this thread https://github.com/dequelabs/axe-core/issues/991
I'd appreciate your feedback.

**Comment by straker** [comment]
@zolza should have been fixed. I believe the error your getting is for the `landmark-one-main` rule while these fixes were for the `region` rule.

**Comment by zolza** [comment]
@straker thanks for getting back to me, the error I'm getting is `landmark-one-main` - do I need to duplicate the main landmark on my dialog? It doesn't seem like the right thing to do. 
Also, I do have a <main> element on my page, it's got aria-hidden=true on ancestor when the dialog shows which I thought is the expected behaviour?
When looking into dialog example here: https://dequeuniversity.com/library/aria/simple-dialog and clicking on the Show dialog button, it shows the same error `landmark-one-main` with the same issue with <main> ancestor getting aria-hidden=true when dialog shows.
I appreciate it may not be related to this thread, shall I create another issue?

**Comment by kensgists** [comment]
@zolza or @straker , did you ever create another issue for the dialog flagging a landmark-one-main issue? We are still seeing this in the latest axe-core version. Thanks!

**Comment by straker** [comment]
@kensgists There is currently not a fix for this. Would you mind opening up a new ticket specifically for `landmark-one-main` and dialogs (with example and/or a page that shows the issue)? That way we can track it better and try to get a fix for it.

**Comment by kensgists** [comment]
@straker Thanks. I have created issue #3359
