### ISSUE TITLE
target property with `:root > div > img` value

### ISSUE THREAD

**Issue by g-yonchev** [dequelabs/axe-core#3109]
Product: axe-core v4.3.2

Expectation: to return a target with which doing `document.querySelector(target[0]);` to return an html element.

Actual: it returns a target with which doing `document.querySelector(target[0]);` results with `null`.

website example: https://kenzdesigns.com.au/
code snippet:
```
<!doctype html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Document Title</title>
    </head>
    <body>
    <div class="line1">Ethnicraft OLD SADDLE range&nbsp;</div>
    <div class="inner-div">
      <div class="col-xs-6 cat_pro_item">
        <a href="3 Seater">
          <div><img src="https://www.kenzdesigns.com.au/image/cache/catalog/Ethnicraft/20084-N701-3-seater-old-saddle-MAIN-145x200.jpg" class="img-responsive"></div>
        </a>
      </div>
      <div class="col-xs-6 cat_pro_item">
        <a href="1 Seater">
          <div><img src="https://www.kenzdesigns.com.au/image/cache/catalog/Ethnicraft/20082-N701-1-seater-old-saddle-main-145x200.jpg" class="img-responsive"></div>
        </a>
      </div>
      <div class="col-xs-6 cat_pro_item">
        <a href="Corner">
          <div><img src="https://www.kenzdesigns.com.au/image/cache/catalog/Ethnicraft/20080-N701-corner-sofa-old-saddle-145x200.jpg" class="img-responsive"></div>
        </a>
      </div>
      <div class="col-xs-6 cat_pro_item">
        <a href="Ottoman">
          <div><img src="https://www.kenzdesigns.com.au/image/cache/catalog/Ethnicraft/20081-N701-footstool-old-saddle-main-1-145x200.jpg" class="img-responsive"></div>
        </a>
      </div>
    </div>
    </body>
    </html>
```

when on this snippet I am doing `axe.run(document, { runOnly: ['image-alt'] });` it returns 
```
{
  violations: [
    {
      id: "image-alt",
      nodes: [
        {
          html: '<img src="https://www.kenzdesigns.com.au/image/cache/catalog/Ethnicraft/20084-N701-3-seater-old-saddle-MAIN-145x200.jpg" class="img-responsive">',
          target: [':root > div > img']
        }
      ]
    }
  ]
}
```

which then doing `document.querySelector(':root > div > img')` it returns `null`.

I am trying to understand if this is expected behaviour or a bug?

**Comment by g-yonchev** [comment]
> Wow! That's an odd one. No idea how that might happen, but clearly `:root > div > img` is wrong. I'll look into it!

Thanks, @WilcoFiers

**Comment by padmavemulapati** [comment]
Verified with the latest dev branch code,
we fixed axe-core to not return that selector anymore
![image](https://user-images.githubusercontent.com/47409579/147953338-970caf28-7079-444b-bded-8e509ce81b5b.png)

**Comment by g-yonchev** [comment]
Hello, any updates on this? I am still experiencing the same issue with latest module version `axe-core 4.3.5`?

**Comment by straker** [comment]
We've completed the changes for this issue and a release is planned for the end of the month that will incorporate the fix.
